# instance:       concourse.int.adgear.com
# pipeline_name:  zql
# team:           data
---
resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

  - name: commit-status
    type: docker-image
    source:
      repository: dpb587/github-status-resource
      tag: master

resources:
  - name: common-tasks-repo
    type: git
    source:
      uri: git@github.com:adgear/common-tasks.git
      private_key: ((adgear-concourse.ssh_private_key))

  - name: zql-pr
    type: pull-request
    source:
      repository: adgear/zql
      access_token: "((adgear-concourse.access_token))"
    check_every: 1h
    webhook_token: "((webhook_token))"

  - name: zql-tags
    type: git
    source:
      private_key: ((adgear-concourse.ssh_private_key))
      repository_name: adgear/zql
      uri: git@github.com:adgear/zql.git
      tag_filter: "*.*.*"

  - name: zql-commit-status
    type: commit-status
    source:
      repository:   adgear/zql
      access_token: ((adgear-concourse.access_token))
      context: concourse/ci

jobs:
  - name: build-pr
    plan:
      - in_parallel:
          steps:
            - get: common-tasks-repo
            - get: zql-pr
              trigger: true
              version: every
      - put: zql-pr
        params:
          path:   zql-pr
          status: pending
      - task: mvn-build
        file: common-tasks-repo/mvn-build/latest/mvn-build.yml
        input_mapping:
          source: zql-pr
        params: { EXPORT_VOLUMES: false }
        on_success:
          put: zql-pr
          params:
            path:   zql-pr
            status: success
        on_failure:
          put: zql-pr
          params:
            path:   zql-pr
            status: failure

  - name: build-tags
    plan:
      - in_parallel:
          steps:
            - get: common-tasks-repo
            - get: zql-tags
              trigger: true
              version: every
      - do:
        - task: mvn-build
          file: common-tasks-repo/mvn-build/latest/mvn-build.yml
          input_mapping:
            source: zql-tags
          params:
            IS_RELEASE: true
            EXPORT_VOLUMES: false
        on_success:
          put: zql-commit-status
          params:
            state:  success
            commit: zql-tags
        on_failure:
          put: zql-commit-status
          params:
            state:  failure
            commit: zql-tags
